name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            export PATH=/home/markos-server/.nvm/versions/node/v24.14.0/bin:$PATH
            cd ~/projects/mark0scom
            git pull origin main
            npm install
            npm run build
            sudo cp -r dist/* /var/www/mark0scom/
